#####################################################
# Fichero Dockerfile para Imagen Base jboss/wildfly #
#####################################################

FROM jboss/wildfly

## Añadimos alguno de los proyectos de ejemplo (*.war) a "deployment"
ADD PrimerProyecto.war /opt/jboss/wildfly/standalone/deployments/